version: '3.8'

services:
  api:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: ManagementProduct
    ports:
      - "8080:8080"
    environment:
      - ASPNETCORE_ENVIRONMENT=Production
      - ASPNETCORE_URLS=http://+:8080
      - Jwt__Key=your-super-secret-key-minimum-32-characters!!
      - Jwt__Issuer=ProductAPI
      - Jwt__Audience=ProductAPIUsers
    volumes:
      - sqlite_data:/app
    restart: unless-stopped

volumes:
  sqlite_data: